language: "es-la"
invalid-message-path: "No message for path '%path%'."
# Round settings
game-round:
  start-countdown: 3
  round-time: 120
  end-intermission: 3
  player-immobilization: 3
  chest-drop: false
score-manager:
  value-per-order: 30
order-manager:
  time-for-next-order: 20
  order-timeout: 80
  order-stack-limit: 5
  bonus-probability: 0.2
# Sound settings
round-starting:
  countdown-instrument: BIT
  countdown-tone:
    octave: 1
    tone: F
    sharped: true
  start-tone:
    octave: 2
    tone: F
    sharped: true
round-timer:
  time-running-out-sound: BLOCK_ANVIL_PLACE
  finish-sound: BLOCK_ANVIL_USE
order-sounds:
  order-entry-sound: BLOCK_AMETHYST_CLUSTER_HIT
  delivered-order-sound: ENTITY_PLAYER_LEVELUP
  lost-order-sound: BLOCK_ENCHANTMENT_TABLE_USE