main: org.cyanx86.OverCrafted
version: 1.0.0
name: OverCrafted
author: CYANx86
api-version: 1.20

commands:

  overcrafted:
    description: Comando principal
    aliases:
      - ocf

  gamearea:
    description: Administra GameAreas.
    aliases:
      - ga
