main: org.cyanx86.OverCrafted
version: 1.0.0
name: OverCrafted
author: CYANx86
api-version: 1.20

commands:
  round:
    decription: "Round controls."
    aliases:
      - rnd
      - ro
  kitchen:
    description: "Manage kitchens."
    aliases:
      - ktc
      - kt
  recipes:
    description: "Manage kitchen recipes."
    aliases:
      - rcp
      - rp

permissions:
  overcrafted.*:
    description: "Permiso general."
    default: op
  manager:
    description: "Permiso de administrador"